DROP TABLE IF EXISTS users;

--CREATE EXTENSION IF NOT EXISTS pgcrypto;
--CREATE EXTENSION IF NOT EXISTS intarray;

CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(30) NOT NULL UNIQUE,
	pass BYTEA NOT NULL,
	email VARCHAR(30) NOT NULL UNIQUE,
	token_value BYTEA
);

